id: I0A14B11F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T21:25:21+00:00'
last_modified: '2022-06-07T12:25:26.070547+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W19610
  title: སྡོམ་གསུམ་རབ་དབྱེའི་འགྲེལ་པ་ཆེན་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8ACD:
      image_group_id: I4328
      title: ''
      total_pages: 512
      order: 1
      base_file: 8ACD.txt
    186B:
      image_group_id: I4340
      title: ''
      total_pages: 528
      order: 2
      base_file: 186B.txt
    124A:
      image_group_id: I4341
      title: ''
      total_pages: 572
      order: 3
      base_file: 124A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
